"use client";
import Head from "next/head";
import Section1 from "../components/Section1";
import Section2 from "../components/Section2";
import Section3 from "../components/Section3";
import Section4 from "../components/Section4";
import { useEffect } from "react";

const LandingPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>Webicient</title>
        <meta name="Webicient Landing Page" content="Generated by Oussama" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Section1 />
        <Section2 />
        <Section3 />
        <Section4 />
      </main>
      <footer>{/* Add footer content */}</footer>
    </>
  );
};

export default LandingPage;
