import Head from "next/head";
import styles from "../../styles/Layout.module.css";

const FirstPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>Webicient</title>
        <meta name="Webicient Landing Page" content="Generated by Oussama" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.textOverlay}>
          <h1>Lorem ipsum dolor sit amet, consec</h1>
          <p>
            Aliquam eu malesuada turpis, eu interdum nibh. Etiam tristique erat
            in ligula consequat malesuada.
          </p>
          <p>Praesent posuere vestibulum neque ac posuere.</p>
        </div>
      </header>
      <main>{children}</main>
      <footer>{/* Add footer content */}</footer>
    </>
  );
};

export default FirstPage;
